apiVersion: v1
baseDomain: '$OCP_BASE_DOMAIN'
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    ovirt:
      affinityGroupsNames: []
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    ovirt:
      affinityGroupsNames: []
  replicas: 3
metadata:
  name: '$OCP_CLUSTER_NAME'
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.2.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  ovirt:
    affinityGroups: []
    api_vip: 10.0.0.1 # Replace
    ingress_vip: 10.0.0.2 # Replace
    ovirt_cluster_id: 00000000-0000-0000-0000-000000000000 # Replace
    ovirt_network_name: ovirtmgmt
    ovirt_storage_domain_id: 00000000-0000-0000-0000-000000000000 # Replace
    vnicProfileID: 0000000a-000a-000a-000a-000000000000 # Replace
publish: External
sshKey: '$OCP_SSH_KEY'
pullSecret: '$OCP_PULL_SECRET'

